### ISSUE TITLE
Original WAV files

### ISSUE THREAD

**Issue by psmitty7373** [aizquier/voyagerimb#1]
Do you still have the original WAV files available?

**Comment by aizquier** [comment]
Sure! Send me an email to aizquier@gmail.com , so I could reply you with a link to the files (Apparently the original audio is copyright protected, that's why I could not publish the files here).

**Comment by ryanseddon** [comment]
It seems to be in the public domain and available here https://archive.org/details/Voyager1

**Comment by aizquier** [comment]
> It seems to be in the public domain and available here https://archive.org/details/Voyager1

Unfortunately the version posted in archive.org has the channels left/right mixed in one monophonic file.

**Comment by ryanseddon** [comment]
Ah bummer, can I email you too to get the version you have?

**Comment by aizquier** [comment]
Yes please!! :)

**Comment by caio-peixoto** [comment]
This link seems to have all the .wav files:
[https://drive.google.com/drive/folders/0B0Swx_1rwA6XcFFLc29ncFJSZmM](https://drive.google.com/drive/folders/0B0Swx_1rwA6XcFFLc29ncFJSZmM)
